### ISSUE TITLE
Implement Windows x64 code generation

### ISSUE THREAD

**Issue by polsys** [polsys/cle#6]
The last chunk of the initial vertical slice.
- [x] Lower the IR to an architecture-specific format
- [x] Implement a trivial register allocator for initial bringup
- [x] Implement a Portable Executable emitter
- [x] Implement an emitter that supports fixups and optionally produces a disassembly stream
- [x] Emit "good enough" assembly code for the IR
- [x] Implement a proper register allocator based on SSA guarantees (followup issue: #54)
- [x] Look into producing PDB symbols (issue: #55)
- [x] Implement a simple integration test suite
- [x] Implement the IR ops not covered by PR #53
- [x] Implement more `Functional` test cases
- [x] Benchmark the backend (extend the end-to-end test, add one for register allocator)
- [x] Fix up the hexadecimal style
